name: ES|QL Validation
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target Detection Rules Branch (e.g. esql_testing)'
        required: true
        default: 'esql_testing'
      rule_id:
        description: 'Rule ID to validate against esql'
        required: false

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    env:
      STACK_VERSION: 9.1.2

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: elastic-container
          repository: eric-forte-elastic/elastic-container

      - name: Build and run containers
        run: |
          echo "I am just testing the pipeline"
